name: Create Pull Request Workflow

on:
  push:
    branches:
      - testBranch  # This should be the branch where changes are made

env:
  SOURCE_BRANCH: testBranch  # Source branch for the pull
  DESTINATION_BRANCH: main  # Target branch in the main repository
  DESTINATION_REPO_OWNER: DonLofto  # Owner of the main repository
  DESTINATION_REPO_NAME: DevOpsProject  # Name of the main repository

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          source_branch: ${{ env.SOURCE_BRANCH }}
          destination_branch: ${{ env.DESTINATION_BRANCH }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Automated Pull Request"
          pr_body: "This is an automated pull request to merge changes from ${{ env.SOURCE_BRANCH }} to ${{ env.DESTINATION_BRANCH }}."
          destination_repo_owner: ${{ env.DESTINATION_REPO_OWNER }}
          destination_repo_name: ${{ env.DESTINATION_REPO_NAME }}